---
title: 'Part 1: Conditional statements and for loops'
author: "Erica Bishop"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

###Conditional Statments

##Task 1

```{r}
pm2_5 <- 189

if (pm2_5 < 100) {
  print("Low to moderate risk") 
} else if (pm2_5 >= 100 & pm2_5 <= 150) {
  print("Unhealthy for sensitive groups")
} else if (pm2_5 > 150) {
  print("Health risk present")
}


```

##Task 2

```{r}

species <- "blue whale"

if (str_detect(species, "whale")) {
  print("You found a whale!")
}

```

##Task 3

```{r}
max_airtemp_c <- 24.1

if (max_airtemp_c > 27) {
  print("Temperature too high!")
} else if (
  max_airtemp_c <= 27) {
  print("Temperature OK")
}


```

##Task 4

```{r}
base_burrito <- 6.50

main_ingredient <- c("veggie", "chicken", "steak")

burrito_cost <- vector(mode = "numeric", length = length(main_ingredient))

for (i in seq_along(main_ingredient)) {
  if (main_ingredient[i] == "veggie") {
    burrito_cost[i] <- base_burrito
  } else if (main_ingredient[i] == "chicken") {
    burrito_cost[i] <- base_burrito + 3
  } else if (main_ingredient[i] == "steak") {
    burrito_cost[i] <- base_burrito + 3.25
  }
  burrito_cost[i]
}

```

###For loops

##Task 5

```{r}
fish <- c(8, 10, 12, 23)

for (i in seq_along(fish)) {
  fish_proportion = fish[i] / sum(fish) *100
  print(fish_proportion)
}

```

##Task 6

```{r}

for(i in seq_along(month.name)) {
  print(paste(month.name[i], "is month", i))}



```


